name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Collatz Conjecture Test
      id: collatz-conjecture-test
      uses: education/autograding-command-grader@v1
      with:
        test-name: Collatz Conjecture Test
        setup-command: sudo apt-get install rustc cargo
        command: cargo test
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        COLLATZ-CONJECTURE-TEST_RESULTS: "${{steps.collatz-conjecture-test.outputs.result}}"
      with:
        runners: collatz-conjecture-test
